(in-package :cl-perec-test)

(defsuite* (test/persistence/table :in test/persistence))

(def test test/persistence/table/persistent-object ()
  (is (not (primary-table-of (find-class 'persistent-object)))))

(def pclass* table-t1-test ()
  ((name :type string)))
   
(def pclass* table-t2-test (table-t1-test)
  ((name)))

(def test test/persistence/table/inheritance ()
  (is (not (null (find "_name" (columns-of (primary-table-of (find-class 'table-t1-test))) :key #'rdbms::name-of :test #'string=))))
  (is (null (find "_name" (columns-of (primary-table-of (find-class 'table-t2-test))) :key #'rdbms::name-of :test #'string=))))

(def pclass* table-a1-test ()
  ()
  (:abstract #t))
   
(def pclass* table-b1-test (table-a1-test)
  ())

(def pclass* table-c1-test (table-a1-test)
  ())

(def pclass* table-a2-test ()
  ()
  (:abstract #t))

(def pclass* table-b2-test (table-a2-test)
  ())

(def pclass* table-c2-test (table-a2-test)
  ())

(def pclass* table-d2-test (table-b2-test table-c2-test)
  ())

(def test test/persistence/table/primary-table ()
  (bind ((a1 (find-class 'table-a1-test))
         (b1 (find-class 'table-b1-test))
         (c1 (find-class 'table-c1-test))
         (a2 (find-class 'table-a2-test))
         (b2 (find-class 'table-b2-test))
         (c2 (find-class 'table-c2-test))
         (d2 (find-class 'table-d2-test)))
    (mapc #'finalize-inheritance (list a1 b1 c1 a2 b2 c2 d2))

    ;; checks for a1
    (is (null (primary-table-of a1)))
    (is (null (data-tables-of a1)))
    (is (equal (list :append (primary-table-of c1) (primary-table-of b1))
               (primary-tables-of a1)))

    ;; checks for b1
    (is (not (null (primary-table-of b1))))
    (is (equal (list (primary-table-of b1))
               (data-tables-of b1)))
    (is (equal (list :append (primary-table-of b1))
               (primary-tables-of b1)))
 
    ;; checks for a2
    (is (null (primary-table-of a2)))
    (is (null (data-tables-of a2)))
    (is (equal (list :union (primary-table-of c2) (primary-table-of b2))
               (primary-tables-of a2)))

    ;; checks for b2
    (is (not (null (primary-table-of b2))))
    (is (equal (list (primary-table-of b2))
               (data-tables-of b2)))
    (is (equal (list :append (primary-table-of b2))
               (primary-tables-of b2)))

    ;; checks for d2
    (is (not (null (primary-table-of d2))))
    (is (equal (list (primary-table-of d2) (primary-table-of b2) (primary-table-of c2))
               (data-tables-of d2)))
    (is (equal (list :append (primary-table-of d2))
               (primary-tables-of d2)))))

(defsuite* (test/persistence/table/store :in test/persistence/table))

(defsuite* (test/persistence/table/store/x :in test/persistence/table/store))

(def pclass* table-x1-test ()
  ((s1 #f :type boolean))
  (:abstract #t)
  (:direct-store :down))

(def pclass* table-x2-test (table-x1-test)
  ((s2 #t :type boolean)))

(def pclass* table-x3-test (table-x2-test)
  ((s3 #f :type boolean)))

(def pclass* table-x4-test (table-x1-test)
  ((s2 #f :type boolean))
  (:abstract #t)
  (:direct-store :down))

(def pclass* table-x5-test (table-x4-test)
  ((s3 #f :type boolean)))

(def pclass* table-x6-test (table-x1-test)
  ((s2 #f :type boolean))
  (:abstract #t))

(def pclass* table-x7-test (table-x6-test)
  ((s3 #f :type boolean)))

(def test test/persistence/table/store/x/1 ()
  (with-transaction
    (bind ((x1-class (find-class 'table-x1-test))
           (x1-table (primary-table-of x1-class))
           (x1-view (primary-view-of x1-class))
           (x1-s1-slot (find-slot 'table-x1-test 's1)))
      (is (equal (effective-store-of x1-class)
                 '((table-x1-test table-x1-test))))
      (is (eq (primary-class-of x1-s1-slot) x1-class))
      (is (null x1-table))
      (is (not (null x1-view))))))

(def test test/persistence/table/store/x/2 ()
  (with-transaction
    (bind ((x2-class (find-class 'table-x2-test))
           (x2-table (primary-table-of x2-class))
           (x2-view (primary-view-of x2-class))
           (x2-s1-slot (find-slot 'table-x2-test 's1))
           (x2-s2-slot (find-slot 'table-x2-test 's2)))
      (is (equal (effective-store-of x2-class)
                 '((table-x2-test table-x2-test) (table-x1-test table-x2-test))))
      (is (eq (primary-class-of x2-s1-slot) x2-class))
      (is (eq (primary-class-of x2-s2-slot) x2-class))
      (is (not (null x2-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of x2-table))
                 '("_oid" "_s1" "_s2")))
      (is (null x2-view))
      (finishes (make-instance 'table-x2-test)))))

(def test test/persistence/table/store/x/3 ()
  (with-transaction
    (bind ((x2-class (find-class 'table-x2-test))
           (x3-class (find-class 'table-x3-test))
           (x3-table (primary-table-of x3-class))
           (x3-view (primary-view-of x3-class))
           (x3-s1-slot (find-slot 'table-x3-test 's1))
           (x3-s2-slot (find-slot 'table-x3-test 's2))
           (x3-s3-slot (find-slot 'table-x3-test 's3)))
      (is (equal (effective-store-of x3-class)
                 '((table-x3-test table-x3-test) (table-x2-test table-x2-test) (table-x1-test table-x2-test))))
      (is (eq (primary-class-of x3-s1-slot) x2-class))
      (is (eq (primary-class-of x3-s2-slot) x2-class))
      (is (eq (primary-class-of x3-s3-slot) x3-class))
      (is (not (null x3-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of x3-table))
                 '("_oid" "_s3")))
      (is (null x3-view))
      (finishes (make-instance 'table-x3-test)))))

(def test test/persistence/table/store/x/4 ()
  (with-transaction
    (bind ((x4-class (find-class 'table-x4-test))
           (x4-table (primary-table-of x4-class))
           (x4-view (primary-view-of x4-class))
           (x4-s1-slot (find-slot 'table-x4-test 's1))
           (x4-s2-slot (find-slot 'table-x4-test 's2)))
      (is (equal (effective-store-of x4-class)
                 '((table-x4-test table-x4-test) (table-x1-test table-x4-test))))
      (is (eq (primary-class-of x4-s1-slot) x4-class))
      (is (eq (primary-class-of x4-s2-slot) x4-class))
      (is (null x4-table))
      (is (not (null x4-view))))))

(def test test/persistence/table/store/x/5 ()
  (with-transaction
    (bind ((x5-class (find-class 'table-x5-test))
           (x5-table (primary-table-of x5-class))
           (x5-view (primary-view-of x5-class))
           (x5-s1-slot (find-slot 'table-x5-test 's1))
           (x5-s2-slot (find-slot 'table-x5-test 's2))
           (x5-s3-slot (find-slot 'table-x5-test 's3)))
      (is (equal (effective-store-of x5-class)
                 '((table-x5-test table-x5-test) (table-x4-test table-x5-test) (table-x1-test table-x5-test))))
      (is (eq (primary-class-of x5-s1-slot) x5-class))
      (is (eq (primary-class-of x5-s2-slot) x5-class))
      (is (eq (primary-class-of x5-s3-slot) x5-class))
      (is (not (null x5-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of x5-table))
                 '("_oid" "_s1" "_s2" "_s3")))
      (is (null x5-view))
      (finishes (make-instance 'table-x5-test)))))

(def test test/persistence/table/store/x/6 ()
  (with-transaction
    (bind ((x6-class (find-class 'table-x6-test))
           (x6-table (primary-table-of x6-class))
           (x6-view (primary-view-of x6-class))
           (x6-s1-slot (find-slot 'table-x6-test 's1))
           (x6-s2-slot (find-slot 'table-x6-test 's2)))
      (is (equal (effective-store-of x6-class)
                 '((table-x6-test table-x6-test) (table-x1-test table-x6-test))))
      (is (eq (primary-class-of x6-s1-slot) x6-class))
      (is (eq (primary-class-of x6-s2-slot) x6-class))
      (is (not (null x6-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of x6-table))
                 '("_oid" "_s1" "_s2")))
      (is (null x6-view)))))

(def test test/persistence/table/store/x/7 ()
  (with-transaction
    (bind ((x6-class (find-class 'table-x6-test))
           (x7-class (find-class 'table-x7-test))
           (x7-table (primary-table-of x7-class))
           (x7-view (primary-view-of x7-class))
           (x7-s1-slot (find-slot 'table-x7-test 's1))
           (x7-s2-slot (find-slot 'table-x7-test 's2))
           (x7-s3-slot (find-slot 'table-x7-test 's3)))
      (is (equal (effective-store-of x7-class)
                 '((table-x7-test table-x7-test) (table-x6-test table-x6-test) (table-x1-test table-x6-test))))
      (is (eq (primary-class-of x7-s1-slot) x6-class))
      (is (eq (primary-class-of x7-s2-slot) x6-class))
      (is (eq (primary-class-of x7-s3-slot) x7-class))
      (is (not (null x7-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of x7-table))
                 '("_oid" "_s3")))
      (is (null x7-view))
      (finishes (make-instance 'table-x7-test)))))

(defsuite* (test/persistence/table/store/y :in test/persistence/table/store))

(def pclass* table-y1-test ()
  ((s1 #f :type boolean))
  (:abstract #t))

(def pclass* table-y2-test (table-y1-test)
  ())

(def pclass* table-y3-test (table-y1-test)
  ())

(def pclass* table-y4-test (table-y2-test table-y3-test)
  ((s2 #t :type boolean)))

(def test test/persistence/table/store/y/1 ()
  (with-transaction
    (bind ((y1-class (find-class 'table-y1-test))
           (y1-table (primary-table-of y1-class))
           (y1-view (primary-view-of y1-class))
           (y1-s1-slot (find-slot 'table-y1-test 's1)))
      (is (equal (effective-store-of y1-class)
                 '((table-y1-test table-y1-test))))
      (is (eq (primary-class-of y1-s1-slot) y1-class))
      (is (not (null y1-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of y1-table))
                 '("_oid" "_s1")))
      (is (null y1-view)))))

(def test test/persistence/table/store/y/2 ()
  (with-transaction
    (bind ((y1-class (find-class 'table-y1-test))
           (y2-class (find-class 'table-y2-test))
           (y2-table (primary-table-of y2-class))
           (y2-view (primary-view-of y2-class))
           (y2-s1-slot (find-slot 'table-y2-test 's1)))
      (is (equal (effective-store-of y2-class)
                 '((table-y1-test table-y1-test))))
      (is (eq (primary-class-of y2-s1-slot) y1-class))
      (is (null y2-table))
      (is (not (null y2-view)))
      (finishes (make-instance 'table-y2-test)))))

(def test test/persistence/table/store/y/3 ()
  (with-transaction
    (bind ((y1-class (find-class 'table-y1-test))
           (y3-class (find-class 'table-y3-test))
           (y3-table (primary-table-of y3-class))
           (y3-view (primary-view-of y3-class))
           (y3-s1-slot (find-slot 'table-y3-test 's1)))
      (is (equal (effective-store-of y3-class)
                 '((table-y1-test table-y1-test))))
      (is (eq (primary-class-of y3-s1-slot) y1-class))
      (is (null y3-table))
      (is (not (null y3-view)))
      (finishes (make-instance 'table-y3-test)))))

(def test test/persistence/table/store/y/4 ()
  (with-transaction
    (bind ((y1-class (find-class 'table-y1-test))
           (y4-class (find-class 'table-y4-test))
           (y4-table (primary-table-of y4-class))
           (y4-view (primary-view-of y4-class))
           (y4-s1-slot (find-slot 'table-y4-test 's1))
           (y4-s2-slot (find-slot 'table-y4-test 's2)))
      (is (equal (effective-store-of y4-class)
                 '((table-y4-test table-y4-test) (table-y1-test table-y1-test))))
      (is (eq (primary-class-of y4-s1-slot) y1-class))
      (is (eq (primary-class-of y4-s2-slot) y4-class))
      (is (not (null y4-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of y4-table))
                 '("_oid" "_s2")))
      (is (null y4-view))
      (finishes (make-instance 'table-y4-test)))))

(defsuite* (test/persistence/table/store/z :in test/persistence/table/store))

(def pclass* table-z1-test ()
  ((s1 #f :type boolean))
  (:abstract #t)
  (:direct-store :down))

(def pclass* table-z2-test (table-z1-test)
  ((s2 #f :type boolean))
  (:direct-store (table-z1-test table-z1-test)))

(def pclass* table-z3-test (table-z1-test)
  ((s2 #f :type boolean))
  (:direct-store (table-z1-test table-z1-test)))

(def pclass* table-z4-test (table-z2-test table-z3-test)
  ((s3 #t :type boolean)))

(def pclass* table-z5-test (table-z1-test)
  ((s2 #t :type boolean)))

(def test test/persistence/table/store/z/1 ()
  (with-transaction
    (bind ((z1-class (find-class 'table-z1-test))
           (z1-table (primary-table-of z1-class))
           (z1-view (primary-view-of z1-class))
           (z1-s1-slot (find-slot 'table-z1-test 's1)))
      (is (equal (effective-store-of z1-class)
                 '((table-z1-test table-z1-test))))
      (is (eq (primary-class-of z1-s1-slot) z1-class))
      (is (not (null z1-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of z1-table))
                 '("_oid" "_s1")))
      (is (null z1-view)))))

(def test test/persistence/table/store/z/2 ()
  (with-transaction
    (bind ((z1-class (find-class 'table-z1-test))
           (z2-class (find-class 'table-z2-test))
           (z2-table (primary-table-of z2-class))
           (z2-view (primary-view-of z2-class))
           (z2-s1-slot (find-slot 'table-z2-test 's1))
           (z2-s2-slot (find-slot 'table-z2-test 's2)))
      (is (equal (effective-store-of z2-class)
                 '((table-z2-test table-z2-test) (table-z1-test table-z1-test))))
      (is (eq (primary-class-of z2-s1-slot) z1-class))
      (is (eq (primary-class-of z2-s2-slot) z2-class))
      (is (not (null z2-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of z2-table))
                 '("_oid" "_s2")))
      (is (null z2-view))
      (finishes (make-instance 'table-z2-test)))))

(def test test/persistence/table/store/z/3 ()
  (with-transaction
    (bind ((z1-class (find-class 'table-z1-test))
           (z3-class (find-class 'table-z3-test))
           (z3-table (primary-table-of z3-class))
           (z3-view (primary-view-of z3-class))
           (z3-s1-slot (find-slot 'table-z3-test 's1))
           (z3-s2-slot (find-slot 'table-z3-test 's2)))
      (is (equal (effective-store-of z3-class)
                 '((table-z3-test table-z3-test) (table-z1-test table-z1-test))))
      (is (eq (primary-class-of z3-s1-slot) z1-class))
      (is (eq (primary-class-of z3-s2-slot) z3-class))
      (is (not (null z3-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of z3-table))
                 '("_oid" "_s2")))
      (is (null z3-view))
      (finishes (make-instance 'table-z3-test)))))

(def test test/persistence/table/store/z/4 ()
  (with-transaction
    (bind ((z1-class (find-class 'table-z1-test))
           (z2-class (find-class 'table-z2-test))
           (z4-class (find-class 'table-z4-test))
           (z4-table (primary-table-of z4-class))
           (z4-view (primary-view-of z4-class))
           (z4-s1-slot (find-slot 'table-z4-test 's1))
           (z4-s2-slot (find-slot 'table-z4-test 's2))
           (z4-s3-slot (find-slot 'table-z4-test 's3)))
      (is (equal (effective-store-of z4-class)
                 '((table-z4-test table-z4-test) (table-z2-test table-z2-test) (table-z1-test table-z1-test))))
      (is (eq (primary-class-of z4-s1-slot) z1-class))
      (is (eq (primary-class-of z4-s2-slot) z2-class))
      (is (eq (primary-class-of z4-s3-slot) z4-class))
      (is (not (null z4-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of z4-table))
                 '("_oid" "_s3")))
      (is (null z4-view))
      (finishes (make-instance 'table-z4-test)))))

(def test test/persistence/table/store/z/5 ()
  (with-transaction
    (bind ((z5-class (find-class 'table-z5-test))
           (z5-table (primary-table-of z5-class))
           (z5-view (primary-view-of z5-class))
           (z5-s1-slot (find-slot 'table-z5-test 's1))
           (z5-s2-slot (find-slot 'table-z5-test 's1)))
      (is (equal (effective-store-of z5-class)
                 '((table-z5-test table-z5-test) (table-z1-test table-z5-test))))
      (is (eq (primary-class-of z5-s1-slot) z5-class))
      (is (eq (primary-class-of z5-s2-slot) z5-class))
      (is (not (null z5-table)))
      (is (equal (mapcar 'rdbms::name-of (columns-of z5-table))
                 '("_oid" "_s1" "_s2")))
      (is (null z5-view))
      (finishes (make-instance 'table-z5-test)))))
