;;; -*- mode: Lisp; Syntax: Common-Lisp; -*-
;;;
;;; Copyright (c) 2009 by the authors.
;;;
;;; See LICENCE for details.

(in-package :hu.dwim.perec.documentation)

(def project :hu.dwim.perec :path (hu.dwim.asdf:system-pathname :hu.dwim.perec))

(def method make-project-tab-pages ((component project/detail/inspector) (project (eql (find-project :hu.dwim.perec))))
  (append (call-next-method)
          (list (tab-page/widget (:selector "Documentation")
                  (make-value-inspector (find-book 'user-guide) :initial-alternative-type 'book/text/inspector)))))

(def book user-guide (:title "hu.dwim.perec")
  (chapter (:title "Introduction")
    (chapter (:title "What is hu.dwim.perec")
      )
    (chapter (:title "Why not something else?")
      ))
  (chapter (:title "Supported Platforms")
    (chapter (:title "Operating Systems")
      )
    (chapter (:title "Common Lisp Implementations")
      ))
  (chapter (:title "Instal Guide"))
  (chapter (:title "Connect to Database"))
  (chapter (:title "Tutorial")
    (chapter (:title "Persisting Objects")
      ))
  (chapter (:title "Concepts")
    (chapter (:title "Database")
      )
    (chapter (:title "Transaction")
      )
    (chapter (:title "Persistent Objects")
      )
    (chapter (:title "Transient Objects")
      )
    (chapter (:title "Persistent Types")
      )
    (chapter (:title "Type Mapping")
      )
    (chapter (:title "Cache")
      )
    (chapter (:title "Export")
      )
    (chapter (:title "Query Lanugage")
      )
    (chapter (:title "Query Compiler")
      )
    (chapter (:title "Multi Dimensional Values")
      )))
